CREATE TABLE E_JAGRITI_CASES(
    CASE_NO VARCHAR(255) PRIMARY KEY,
    COMPLAINANT TEXT NOT NULL,
    RESPONDENT TEXT,
    FILING_DATE DATE NOT NULL,
    FIRST_HEARING DATE,
    NEXT_HEARING DATE,
    STAGE VARCHAR(100),
    SCRAPED_AT TIMESTAMPTZ NOT NULL
)